Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')
src	= Glob('*.c')
CPPPATH = [cwd]

objs = []
list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
        
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH) + objs

Return('group')
